export enum AuditActionEnum {
  LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILED = 'AUTH_LOGIN_FAILED',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ACTIVE = 'USER_ACTIVE',
  USER_DEACTIVE = 'USER_DEACTIVE',

  ROLE_ASSIGN = 'ROL_ASIGNAR',
  ROLE_UNASSIGN = 'ROL_DESASIGNAR',
}